version: '3'

services:
  webserver:
    container_name: webserver
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    container_name: node
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "npm install && npm run build:css"]
